# Default values for storage-migration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 334301710522.dkr.ecr.eu-central-1.amazonaws.com/complex-migrations
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "SNAPSHOT-1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi
nodeSelector: {}

tolerations: []

affinity: {}

storage:
  minio:
    secretName: ""
    accesskey: <minio-accesskey>
    secretkey: <minio-secretkey>
    accesskeyName: "access-key"
    secretkeyName: "secret-key"
    endpoint: http://<minio-release-name>-minio.default.svc.cluster.local:9000
  s3:
    secretName: ""
    accesskey: <s3-accesskey>
    secretkey: <s3-secretkey>
    accesskeyName: "s3-access-key"
    secretkeyName: "s3-secret-key"
    endpoint: http://s3.eu-central-1.amazonaws.com
  bucket:
    fromMinioBucket: rp-minio-storage
    toS3Bucket: rp-s3-storage